/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as CanonRouteImport } from './routes/canon'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryIdRouteImport } from './routes/library_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LibraryIdRunRouteImport } from './routes/library_.$id_.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonRoute = CanonRouteImport.update({
  id: '/canon',
  path: '/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library_/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRunRoute = LibraryIdRunRouteImport.update({
  id: '/library_/$id_/run',
  path: '/library/$id/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/canon': typeof CanonRoute
  '/capture': typeof CaptureRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/library/$id': typeof LibraryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/$id/run': typeof LibraryIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/canon': typeof CanonRoute
  '/capture': typeof CaptureRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/library/$id': typeof LibraryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library/$id/run': typeof LibraryIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/canon': typeof CanonRoute
  '/capture': typeof CaptureRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/library_/$id': typeof LibraryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/library_/$id_/run': typeof LibraryIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/canon'
    | '/capture'
    | '/library'
    | '/login'
    | '/library/$id'
    | '/api/auth/$'
    | '/library/$id/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/canon'
    | '/capture'
    | '/library'
    | '/login'
    | '/library/$id'
    | '/api/auth/$'
    | '/library/$id/run'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/canon'
    | '/capture'
    | '/library'
    | '/login'
    | '/library_/$id'
    | '/api/auth/$'
    | '/library_/$id_/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  CanonRoute: typeof CanonRoute
  CaptureRoute: typeof CaptureRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  LibraryIdRoute: typeof LibraryIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LibraryIdRunRoute: typeof LibraryIdRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon': {
      id: '/canon'
      path: '/canon'
      fullPath: '/canon'
      preLoaderRoute: typeof CanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$id': {
      id: '/library_/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$id_/run': {
      id: '/library_/$id_/run'
      path: '/library/$id/run'
      fullPath: '/library/$id/run'
      preLoaderRoute: typeof LibraryIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  CanonRoute: CanonRoute,
  CaptureRoute: CaptureRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  LibraryIdRoute: LibraryIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LibraryIdRunRoute: LibraryIdRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
